### ISSUE TITLE
Password checker

### ISSUE THREAD

**Issue by YehuditWeingarten** [ptr-06/sign-up#5]
My task is to create a tool to check whether a password is valid or not.
When a valid password must contain: lowercase, uppercase, special character, and digit. It must not have a sequence of 3 consecutive members (such as 123 or abc ), and that a symbol does not repeat itself more than twice. The length of the password is at least 8 characters.

**Comment by MentorPTR6** [comment]
@YehuditWeingarten 
Move to a comment what is not relevant to the description.
And add a mention to the recipient like this: @MentorPTR6.
